"""allowed_folders

Revision ID: 141a508530c2
Revises: e90554295847
Create Date: 2026-06-22 15:46:01.082937
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '141a508530c2'
down_revision: str | None = 'e90554295847'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_folders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed_folders')
    # ### end Alembic commands ###
